import esbuild from "esbuild";
import process from "process";
import builtInModules from "builtin-modules";
import fs from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const options = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtInModules],
  format: 'cjs',
  target: 'ES6',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
};

if (prod) {
  // Production build
  await esbuild.build(options);
  // Add module.exports to the end of main.js
  let mainJs = fs.readFileSync('main.js', 'utf-8');
  if (!mainJs.includes('module.exports')) {
    mainJs = mainJs.replace('})();', '})();\nmodule.exports = module.exports.default || module.exports;');
    fs.writeFileSync('main.js', mainJs);
  }
} else {
  // Development build with watch
  const context = await esbuild.context(options);
  await context.watch();
}
